FROM node:20

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libnss3 \
    libnspr4 \
    libxkbcommon0 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libgbm1 \
    libasound2 \
    libpangocairo-1.0-0 \
    libpango-1.0-0 \
    libcairo2 \
    libx11-xcb1 \
    libxfixes3 \
    libxshmfence1 \
    libx11-6 \
    libxext6 \
    libxrender1 \
    libgtk-3-0 \
    libdrm2 \
    libxinerama1 \
    libxi6 \
    fonts-liberation \
    ca-certificates \
    wget \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build:server

EXPOSE 3001

CMD ["node", "dist/services/services.js"]